variables:
  - name: artifactsPath
    value: '$(Build.ArtifactStagingDirectory)'
  - name: tempPath
    value: '$(Agent.TempDirectory)/ymltemp'
  - name: archiveFile
    value: 'archive.zip'
  - name: pipelinesPath
    value: '$(System.DefaultWorkingDirectory)/.github/pipelines'
  - name: infrastructurePath
    value: '$(System.DefaultWorkingDirectory)/.github/infrastructure'
  - name: srcPath
    value: '$(System.DefaultWorkingDirectory)'