trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - /*
    exclude:
    - .github/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../variables/common.yml

stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: variables/development.yml
      
    jobs:    
      - job: package_web
        steps:
          - template: steps/webstatic-pack-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              archiveFile: '$(archiveFile)'
              srcPath: '$(srcPath)'

      - job: deploy_web
        dependsOn: package_web
        steps:
          - template: steps/web-deploy-steps.yml
            parameters:
              artifactsPath: '$(artifactsPath)'
              archiveFile: '$(archiveFile)'
              webName: '$(webName)'
              subscriptionId: '$(subscriptionId)'
              subscriptionName: '$(subscriptionName)'

      - job: settings_web
        dependsOn: deploy_web
        steps:
          - template: steps/web-settings-steps.yml
            parameters:
              subscriptionName: '$(subscriptionName)'
              rgEnvironment: '$(rgEnvironment)'
              webName: '$(webName)'